export const FEATURE_ID = 'feature:[0-9a-f-]{36}/[0-9a-f-]{36}'
export const LAYER_ID = 'layer:[0-9a-f-]{36}'
export const PLACE_ID = 'place:[0-9a-f-]{36}'
export const GROUP_ID = 'group:[0-9a-f-]{36}'
export const SYMBOL_ID = 'symbol:[A-Z-*]{10}'
export const LINK_ID = 'link:[0-9a-f-]{36}'
export const PROJECT_ID = 'project:[0-9a-f-]{36}'
export const FIELD_ID = 'field:[0-9a-f-]{36}'
